//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_Clinica_Medica
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSULTAS()
        {
            this.CONSULTA_DOENCA = new HashSet<CONSULTA_DOENCA>();
            this.CONSULTAS1 = new HashSet<CONSULTAS>();
            this.EXAMES_SOLICITADOS = new HashSet<EXAMES_SOLICITADOS>();
            this.PACIENTE_HISTORICO_CLINICO = new HashSet<PACIENTE_HISTORICO_CLINICO>();
            this.RECEITAS = new HashSet<RECEITAS>();
        }
    
        public int ID { get; set; }
        public int ID_MEDICO { get; set; }
        public int ID_PACIENTE { get; set; }
        public System.DateTime DATA_INICIO { get; set; }
        public System.DateTime DATA_FIM { get; set; }
        public bool REALIZADA { get; set; }
        public bool RETORNO { get; set; }
        public Nullable<int> ID_CONSULTA_RETORNO { get; set; }
        public Nullable<bool> CANCELADA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA_DOENCA> CONSULTA_DOENCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTAS> CONSULTAS1 { get; set; }
        public virtual CONSULTAS CONSULTAS2 { get; set; }
        public virtual MEDICOS MEDICOS { get; set; }
        public virtual PACIENTES PACIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMES_SOLICITADOS> EXAMES_SOLICITADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_HISTORICO_CLINICO> PACIENTE_HISTORICO_CLINICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEITAS> RECEITAS { get; set; }
    }
}
