//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_Clinica_Medica
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMES_SOLICITADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMES_SOLICITADOS()
        {
            this.EXAME_RESULTADO = new HashSet<EXAME_RESULTADO>();
        }
    
        public int ID { get; set; }
        public int ID_EXAME { get; set; }
        public int ID_CONSULTA { get; set; }
    
        public virtual CONSULTAS CONSULTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAME_RESULTADO> EXAME_RESULTADO { get; set; }
        public virtual EXAMES EXAMES { get; set; }
    }
}
