//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_Clinica_Medica
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICOS()
        {
            this.CONSULTAS = new HashSet<CONSULTAS>();
            this.MEDICO_CLINICA = new HashSet<MEDICO_CLINICA>();
            this.MEDICO_ESPECIALIDADE = new HashSet<MEDICO_ESPECIALIDADE>();
            this.MEDICO_HORARIO_ATENDIMENTO = new HashSet<MEDICO_HORARIO_ATENDIMENTO>();
        }
    
        public int ID { get; set; }
        public string CRM { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTAS> CONSULTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_CLINICA> MEDICO_CLINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_ESPECIALIDADE> MEDICO_ESPECIALIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_HORARIO_ATENDIMENTO> MEDICO_HORARIO_ATENDIMENTO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
